language: ruby
gemfile:
  - Gemfile
rvm:
  - 2.2.2
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"
before_script:
  - mv .env.travis .env
  - cp config/database.yml.sample config/database.yml
  - rm db/seeds.rb
  - mv db/seeds.travis.rb db/seeds.rb
  - npm install
script:
  - bundle exec rake db:migrate
  - bundle exec rake travis:specs
bundler_args: ""
sudo: false
cache: bundler
